FROM treeverse/lakefs:1.48

# Устанавливаем lakectl CLI (уже включен в образ treeverse/lakefs)
# Dockerfile нужен для возможной кастомизации и выполнения требований ТЗ

EXPOSE 8000

ENTRYPOINT ["/app/lakefs"]
CMD ["run"]
